export const countriesDataEn = [
    {
      name: 'France',
      population: '67.1 million',
      currency: 'Euro (EUR)',
      language: 'French',
      capital: 'Paris',
      area: '551,695 km²',
      continent: 'Europe',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_France.svg',
    },
    {
      name: 'Spain',
      population: '47.3 million',
      currency: 'Euro (EUR)',
      language: 'Spanish',
      capital: 'Madrid',
      area: '505,990 km²',
      continent: 'Europe',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Spain.svg',
    },
    {
      name: 'United States',
      population: '331 million',
      currency: 'Dollar (USD)',
      language: 'English',
      capital: 'Washington, D.C.',
      area: '9.83 million km²',
      continent: 'North America',
      flag: 'https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg',
    },
    {
      name: 'Italy',
      population: '60.4 million',
      currency: 'Euro (EUR)',
      language: 'Italian',
      capital: 'Rome',
      area: '301,340 km²',
      continent: 'Europe',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/0/03/Flag_of_Italy.svg',
    },
    {
      name: 'China',
      population: '1.41 billion',
      currency: 'Yuan (CNY)',
      language: 'Chinese',
      capital: 'Beijing',
      area: '9.597 million km²',
      continent: 'Asia',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg',
    },
    {
      name: 'United Kingdom',
      population: '67.1 million',
      currency: 'Pound (GBP)',
      language: 'English',
      capital: 'London',
      area: '242,495 km²',
      continent: 'Europe',
      flag: 'https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg',
    },
    {
      name: 'Mexico',
      population: '126 million',
      currency: 'Mexican Peso (MXN)',
      language: 'Spanish',
      capital: 'Mexico City',
      area: '1.96 million km²',
      continent: 'North America',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg',
    },
    {
      name: 'Canada',
      population: '37.7 million',
      currency: 'Canadian Dollar (CAD)',
      language: 'English, French',
      capital: 'Ottawa',
      area: '9.98 million km²',
      continent: 'North America',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Canada_%28Pantone%29.svg',
    },
    {
      name: 'Turkey',
      population: '84.3 million',
      currency: 'Turkish Lira (TRY)',
      language: 'Turkish',
      capital: 'Ankara',
      area: '783,356 km²',
      continent: 'Asia',
      flag: 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg',
    },
    {
      name: 'Germany',
      population: '83.2 million',
      currency: 'Euro (EUR)',
      language: 'German',
      capital: 'Berlin',
      area: '357,022 km²',
      continent: 'Europe',
      flag: 'https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg',
    },{
        name: "Japan",
        population: "126 million",
        currency: "Japanese yen (JPY)",
        language: "Japanese",
        capital: "Tokyo",
        area: "377,975 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Flag_of_Japan.svg"
      },
      {
        name: "Thailand",
        population: "69.8 million",
        currency: "Thai baht (THB)",
        language: "Thai",
        capital: "Bangkok",
        area: "513,120 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg"
      },
      {
        name: "United Arab Emirates",
        population: "9.89 million",
        currency: "Dirham (AED)",
        language: "Arabic",
        capital: "Abu Dhabi",
        area: "83,600 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg"
      },
      {
        name: "Egypt",
        population: "104 million",
        currency: "Egyptian pound (EGP)",
        language: "Egyptian Arabic",
        capital: "Cairo",
        area: "1,010,408 km²",
        continent: "Africa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg"
      },
      {
        name: "Bulgaria",
        population: "6.92 million",
        currency: "Bulgarian lev (BGN)",
        language: "Bulgarian",
        capital: "Sofia",
        area: "110,879 km²",
        continent: "Europe",
        flag: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg"
      },
      {
        name: "Portugal",
        population: "10.3 million",
        currency: "Euro (EUR)",
        language: "Portuguese",
        capital: "Lisbon",
        area: "92,212 km²",
        continent: "Europe",
        flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg"
      },
      {
        name: "Dominican Republic",
        population: "10.9 million",
        currency: "Dominican peso (DOP)",
        language: "Spanish",
        capital: "Santo Domingo",
        area: "48,671 km²",
        continent: "North America",
        flag: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg"
      },
      {
        name: "Tunisia",
        population: "11.7 million",
        currency: "Tunisian dinar (TND)",
        language: "Arabic",
        capital: "Tunis",
        area: "163,610 km²",
        continent: "Africa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg"
      },
      {
        name: "Hungary",
        population: "9.7 million",
        currency: "Hungarian forint (HUF)",
        language: "Hungarian",
        capital: "Budapest",
        area: "93,030 km²",
        continent: "Europe",
        flag: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg"
      },
      {
        name: "Switzerland",
        population: "8.6 million",
        currency: "Swiss franc (CHF)",
        language: "German, French, Italian, Romansh",
        capital: "Bern",
        area: "41,290 km²",
        continent: "Europe",
        flag: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Switzerland.svg"
      },
      {
        name: "Croatia",
        population: "4.07 million",
        currency: "Croatian kuna (HRK)",
        language: "Croatian",
        capital: "Zagreb",
        area: "56,594 km²",
        continent: "Europe",
        flag: "https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg"
      },
      {
        name: "Greece",
        population: "10.4 million",
        currency: "Euro (EUR)",
        language: "Greek",
        capital: "Athens",
        area: "131,957 km²",
        continent: "Europe",
        flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg"
      },
      {
        name: "Austria",
        population: "8.9 million",
        currency: "Euro (EUR)",
        language: "German",
        capital: "Vienna",
        area: "83,879 km²",
        continent: "Europe",
        flag: "https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg"
      },
      {
        name: "India",
        population: "1.366 billion",
        currency: "Indian rupee (INR)",
        language: "Hindi, English, and 21 other languages",
        capital: "New Delhi",
        area: "3,287,263 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_India.svg"
      },
      {
        name: "Cuba",
        population: "11.3 million",
        currency: "Cuban peso (CUP)",
        language: "Spanish",
        capital: "Havana",
        area: "109,884 km²",
        continent: "North America",
        flag: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg"
      },
      {
        name: "Colombia",
        population: "50.9 million",
        currency: "Colombian peso (COP)",
        language: "Spanish",
        capital: "Bogotá",
        area: "1,141,748 km²",
        continent: "South America",
        flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg"
      },
      {
        name: "Czech Republic",
        population: "10.7 million",
        currency: "Czech koruna (CZK)",
        language: "Czech",
        capital: "Prague",
        area: "78,866 km²",
        continent: "Europe",
        flag: "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg"
      },
      {
        name: "Slovakia",
        population: "5.4 million",
        currency: "Euro (EUR)",
        language: "Slovak",
        capital: "Bratislava",
        area: "49,035 km²",
        continent: "Europe",
        flag: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Slovakia.svg"
      },
      {
        name: "Netherlands",
        population: "17.4 million",
        currency: "Euro (EUR)",
        language: "Dutch",
        capital: "Amsterdam",
        area: "41,543 km²",
        continent: "Europe",
        flag: "https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg"
      },  {
        "name": "Belgium",
        "population": "11.5 million",
        "currency": "Euro (EUR)",
        "language": "Dutch, French, German",
        "capital": "Brussels",
        "area": "30,528 km²",
        "continent": "Europe",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg"
      },
      {
        "name": "Brazil",
        "population": "213.3 million",
        "currency": "Brazilian real (BRL)",
        "language": "Portuguese",
        "capital": "Brasília",
        "area": "8,515,767 km²",
        "continent": "South America",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Brazil.svg"
      },
      {
        "name": "Argentina",
        "population": "45.4 million",
        "currency": "Argentine peso (ARS)",
        "language": "Spanish",
        "capital": "Buenos Aires",
        "area": "2,780,400 km²",
        "continent": "South America",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg"
      },
      {
        "name": "Slovenia",
        "population": "2.1 million",
        "currency": "Euro (EUR)",
        "language": "Slovene",
        "capital": "Ljubljana",
        "area": "20,273 km²",
        "continent": "Europe",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/f/f0/Flag_of_Slovenia.svg"
      },
      {
        "name": "Albania",
        "population": "2.9 million",
        "currency": "Albanian lek (ALL)",
        "language": "Albanian",
        "capital": "Tirana",
        "area": "28,748 km²",
        "continent": "Europe",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Albania.svg"
      },
      {
        "name": "Bosnia and Herzegovina",
        "population": "3.3 million",
        "currency": "Bosnian convertible mark (BAM)",
        "language": "Bosnian, Croatian, Serbian",
        "capital": "Sarajevo",
        "area": "51,197 km²",
        "continent": "Europe",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bosnia_and_Herzegovina.svg"
      },
      {
        "name": "Serbia",
        "population": "6.7 million",
        "currency": "Serbian dinar (RSD)",
        "language": "Serbian",
        "capital": "Belgrade",
        "area": "88,361 km²",
        "continent": "Europe",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Serbia.svg"
      },
      {
        "name": "Montenegro",
        "population": "622,000",
        "currency": "Euro (EUR)",
        "language": "Montenegrin",
        "capital": "Podgorica",
        "area": "13,812 km²",
        "continent": "Europe",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Montenegro.svg"
      },
      {
        "name": "North Macedonia",
        "population": "2.1 million",
        "currency": "Macedonian denar (MKD)",
        "language": "Macedonian",
        "capital": "Skopje",
        "area": "25,713 km²",
        "continent": "Europe",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/f/f8/Flag_of_North_Macedonia.svg"
      },
      {
        "name": "Sweden",
        "population": "10.4 million",
        "currency": "Swedish krona (SEK)",
        "language": "Swedish",
        "capital": "Stockholm",
        "area": "450,295 km²",
        "continent": "Europe",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Sweden.svg"
      },
      {
        "name": "Finland",
        "population": "5.5 million",
        "currency": "Euro (EUR)",
        "language": "Finnish, Swedish",
        "capital": "Helsinki",
        "area": "338,455 km²",
        "continent": "Europe",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg"
      },
      {
        "name": "Denmark",
        "population": "5.8 million",
        "currency": "Danish krone (DKK)",
        "language": "Danish",
        "capital": "Copenhagen",
        "area": "42,933 km²",
        "continent": "Europe",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg"
      },
      {
        "name": "Norway",
        "population": "5.4 million",
        "currency": "Norwegian krone (NOK)",
        "language": "Norwegian",
        "capital": "Oslo",
        "area": "385,207 km²",
        "continent": "Europe",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg"
      },
      {
        "name": "Iceland",
        "population": "372,000",
        "currency": "Icelandic króna (ISK)",
        "language": "Icelandic",
        "capital": "Reykjavík",
        "area": "103,000 km²",
        "continent": "Europe",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg"
      },
      {
        "name": "Luxembourg",
        "population": "645,000",
        "currency": "Euro (EUR)",
        "language": "Luxembourgish, French, German",
        "capital": "Luxembourg City",
        "area": "2,586 km²",
        "continent": "Europe",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Luxembourg.svg"
      },
      {
        "name": "Romania",
        "population": "19.3 million",
        "currency": "Romanian leu (RON)",
        "language": "Romanian",
        "capital": "Bucharest",
        "area": "238,397 km²",
        "continent": "Europe",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg"
      },
      {
        "name": "Estonia",
        "population": "1.3 million",
        "currency": "Euro (EUR)",
        "language": "Estonian",
        "capital": "Tallinn",
        "area": "45,227 km²",
        "continent": "Europe",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/8/8f/Flag_of_Estonia.svg"
      },
      {
        "name": "Latvia",
        "population": "1.8 million",
        "currency": "Euro (EUR)",
        "language": "Latvian",
        "capital": "Riga",
        "area": "64,589 km²",
        "continent": "Europe",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Latvia.svg"
      },
      {
        "name": "Lithuania",
        "population": "2.8 million",
        "currency": "Euro (EUR)",
        "language": "Lithuanian",
        "capital": "Vilnius",
        "area": "65,300 km²",
        "continent": "Europe",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Lithuania.svg"
      },
      {
        "name": "Peru",
        "population": "33.7 million",
        "currency": "Peruvian sol (PEN)",
        "language": "Spanish",
        "capital": "Lima",
        "area": "1,285,216 km²",
        "continent": "South America",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Peru.svg"
      },
      {
        "name": "Ecuador",
        "population": "18 million",
        "currency": "United States dollar (USD)",
        "language": "Spanish",
        "capital": "Quito",
        "area": "283,561 km²",
        "continent": "South America",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Ecuador.svg"
      },
      {
        "name": "Chile",
        "population": "18.2 million",
        "currency": "Chilean peso (CLP)",
        "language": "Spanish",
        "capital": "Santiago",
        "area": "756,102 km²",
        "continent": "South America",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/7/78/Flag_of_Chile.svg"
      },  {
        "name": "Bolivia",
        "population": "12.2 million",
        "currency": "Bolivian boliviano (BOB)",
        "language": "Spanish, Quechua, Aymara",
        "capital": "Sucre",
        "area": "1,098,581 km²",
        "continent": "South America",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Bolivia.svg"
      },
      {
        "name": "Paraguay",
        "population": "7.3 million",
        "currency": "Paraguayan guarani (PYG)",
        "language": "Spanish, Guarani",
        "capital": "Asunción",
        "area": "406,752 km²",
        "continent": "South America",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Paraguay.svg"
      },
      {
        "name": "Costa Rica",
        "population": "5.2 million",
        "currency": "Costa Rican colón (CRC)",
        "language": "Spanish",
        "capital": "San José",
        "area": "51,100 km²",
        "continent": "North America",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Costa_Rica_%28state%29.svg"
      },
      {
        "name": "Panama",
        "population": "4.4 million",
        "currency": "Balboa (PAB), US Dollar (USD)",
        "language": "Spanish",
        "capital": "Panama City",
        "area": "75,417 km²",
        "continent": "North America",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Flag_of_Panama.svg"
      },
      {
        "name": "Honduras",
        "population": "10 million",
        "currency": "Honduran lempira (HNL)",
        "language": "Spanish",
        "capital": "Tegucigalpa",
        "area": "112,492 km²",
        "continent": "North America",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/8/82/Flag_of_Honduras.svg"
      },
      {
        "name": "Hong Kong",
        "population": "7.5 million",
        "currency": "Hong Kong dollar (HKD)",
        "language": "Chinese, English",
        "capital": "Hong Kong",
        "area": "1,104 km²",
        "continent": "Asia",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/5/5b/Flag_of_Hong_Kong.svg"
      },
      {
        "name": "Vietnam",
        "population": "97.3 million",
        "currency": "Vietnamese dong (VND)",
        "language": "Vietnamese",
        "capital": "Hanoi",
        "area": "331,212 km²",
        "continent": "Asia",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg"
      },
      {
        "name": "Malaysia",
        "population": "32.7 million",
        "currency": "Malaysian ringgit (MYR)",
        "language": "Malay",
        "capital": "Kuala Lumpur",
        "area": "330,803 km²",
        "continent": "Asia",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg"
      },
      {
        "name": "Ireland",
        "population": "4.9 million",
        "currency": "Euro (EUR)",
        "language": "Irish, English",
        "capital": "Dublin",
        "area": "70,273 km²",
        "continent": "Europe",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Ireland.svg"
      },
      {
        "name": "Indonesia",
        "population": "273.5 million",
        "currency": "Indonesian rupiah (IDR)",
        "language": "Indonesian",
        "capital": "Jakarta",
        "area": "1,904,569 km²",
        "continent": "Asia",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg"
      },
      {
        "name": "Iran",
        "population": "83 million",
        "currency": "Iranian rial (IRR)",
        "language": "Persian",
        "capital": "Tehran",
        "area": "1,648,195 km²",
        "continent": "Asia",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg"
      },
      {
        "name": "Israel",
        "population": "9.2 million",
        "currency": "New Israeli shekel (ILS)",
        "language": "Hebrew",
        "capital": "Jerusalem",
        "area": "20,770 km²",
        "continent": "Asia",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg"
      },
      {
        "name": "Cyprus",
        "population": "1.2 million",
        "currency": "Euro (EUR)",
        "language": "Greek, Turkish",
        "capital": "Nicosia",
        "area": "9,251 km²",
        "continent": "Europe",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cyprus.svg"
      },
      {
        "name": "Morocco",
        "population": "36.9 million",
        "currency": "Moroccan dirham (MAD)",
        "language": "Arabic, Berber",
        "capital": "Rabat",
        "area": "446,550 km²",
        "continent": "Africa",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg"
      },
      {
        "name": "Maldives",
        "population": "530,000",
        "currency": "Maldivian rufiyaa (MVR)",
        "language": "Maldivian",
        "capital": "Malé",
        "area": "298 km²",
        "continent": "Asia",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Maldives.svg"
      },
      {
        "name": "Madagascar",
        "population": "27.7 million",
        "currency": "Malagasy ariary (MGA)",
        "language": "Malagasy, French",
        "capital": "Antananarivo",
        "area": "587,041 km²",
        "continent": "Africa",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Madagascar.svg"
      },
      {
        "name": "Australia",
        "population": "25.4 million",
        "currency": "Australian dollar (AUD)",
        "language": "English",
        "capital": "Canberra",
        "area": "7,692,024 km²",
        "continent": "Australia and Oceania",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Australia.svg"
      },
      {
        "name": "New Zealand",
        "population": "5.1 million",
        "currency": "New Zealand dollar (NZD)",
        "language": "English, Maori",
        "capital": "Wellington",
        "area": "268,021 km²",
        "continent": "Australia and Oceania",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg"
      },
      {
        "name": "Mauritius",
        "population": "1.3 million",
        "currency": "Mauritian rupee (MUR)",
        "language": "English, Mauritian Creole, French",
        "capital": "Port Louis",
        "area": "2,040 km²",
        "continent": "Africa",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Mauritius.svg"
      },
      {
        "name": "Jamaica",
        "population": "2.9 million",
        "currency": "Jamaican dollar (JMD)",
        "language": "English",
        "capital": "Kingston",
        "area": "10,991 km²",
        "continent": "North America",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Jamaica.svg"
      },
      {
        "name": "Nepal",
        "population": "29.1 million",
        "currency": "Nepalese rupee (NPR)",
        "language": "Nepali",
        "capital": "Kathmandu",
        "area": "147,516 km²",
        "continent": "Asia",
        "flag": "https://upload.wikimedia.org/wikipedia/commons/9/97/Flag_of_Nepal.svg"
      },{
        name: "Saudi Arabia",
        population: "34.8 million",
        currency: "Saudi Riyal (SAR)",
        language: "Arabic",
        capital: "Riyadh",
        area: "2,149,690 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg"
      },
      {
        name: "Oman",
        population: "5.1 million",
        currency: "Omani Rial (OMR)",
        language: "Arabic",
        capital: "Muscat",
        area: "309,500 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Oman.svg"
      },
      {
        name: "South Korea",
        population: "51.3 million",
        currency: "South Korean Won (KRW)",
        language: "Korean",
        capital: "Seoul",
        area: "100,210 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg"
      },
      {
        name: "Zimbabwe",
        population: "15.2 million",
        currency: "Zimbabwe Dollar (ZWL)",
        language: "English, Sindebele, Shona",
        capital: "Harare",
        area: "390,757 km²",
        continent: "Africa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Flag_of_Zimbabwe.svg"
      },
      {
        name: "Kenya",
        population: "54.9 million",
        currency: "Kenyan Shilling (KES)",
        language: "Swahili, English",
        capital: "Nairobi",
        area: "580,367 km²",
        continent: "Africa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Kenya.svg"
      },
      {
        name: "Uruguay",
        population: "3.5 million",
        currency: "Uruguayan Peso (UYU)",
        language: "Spanish",
        capital: "Montevideo",
        area: "176,215 km²",
        continent: "South America",
        flag: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Uruguay.svg"
      },
      {
        name: "Philippines",
        population: "111.1 million",
        currency: "Philippine Peso (PHP)",
        language: "Filipino",
        capital: "Manila",
        area: "300,000 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg"
      },
      {
        name: "Kazakhstan",
        population: "18.8 million",
        currency: "Kazakhstani Tenge (KZT)",
        language: "Kazakh, Russian",
        capital: "Nur-Sultan",
        area: "2,724,900 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kazakhstan.svg"
      },
      {
        name: "Georgia",
        population: "3.7 million",
        currency: "Georgian Lari (GEL)",
        language: "Georgian",
        capital: "Tbilisi",
        area: "69,700 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Georgia.svg"
      },
      {
        name: "Azerbaijan",
        population: "10.2 million",
        currency: "Azerbaijani Manat (AZN)",
        language: "Azerbaijani",
        capital: "Baku",
        area: "86,600 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Azerbaijan.svg"
      },
      {
        name: "Ukraine",
        population: "41.8 million",
        currency: "Ukrainian Hryvnia (UAH)",
        language: "Ukrainian",
        capital: "Kyiv",
        area: "603,500 km²",
        continent: "Europe",
        flag: "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg"
      },
      {
        name: "Russia",
        population: "146.7 million",
        currency: "Russian Ruble (RUB)",
        language: "Russian",
        capital: "Moscow",
        area: "17,098,242 km²",
        continent: "Europe and Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Russia.svg"
      },
      {
        name: "Tanzania",
        population: "58.0 million",
        currency: "Tanzanian Shilling (TZS)",
        language: "Swahili, English",
        capital: "Dodoma",
        area: "947,303 km²",
        continent: "Africa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tanzania.svg"
      },
      {
        name: "Qatar",
        population: "2.8 million",
        currency: "Qatari Rial (QAR)",
        language: "Arabic",
        capital: "Doha",
        area: "11,586 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg"
      },
      {
        name: "Malta",
        population: "0.5 million",
        currency: "Euro (EUR)",
        language: "Maltese, English",
        capital: "Valletta",
        area: "316 km²",
        continent: "Europe",
        flag: "https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Malta.svg"
      },
      {
        name: "Sri Lanka",
        population: "21.4 million",
        currency: "Sri Lankan Rupee (LKR)",
        language: "Sinhala, Tamil",
        capital: "Sri Jayawardenepura Kotte",
        area: "65,610 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Sri_Lanka.svg"
      },
      {
        name: "South Africa",
        population: "59.3 million",
        currency: "South African Rand (ZAR)",
        language: "Afrikaans, English, Sotho, Zulu",
        capital: "Pretoria, Cape Town, Bloemfontein",
        area: "1,221,037 km²",
        continent: "Africa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg"
      },
      {
        name: "Jordan",
        population: "10.2 million",
        currency: "Jordanian Dinar (JOD)",
        language: "Arabic",
        capital: "Amman",
        area: "89,342 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Jordan.svg"
      },
      {
        name: "Ghana",
        population: "31.1 million",
        currency: "Ghanaian Cedi (GHS)",
        language: "English",
        capital: "Accra",
        area: "238,535 km²",
        continent: "Africa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg"
      },
      {
        name: "Cameroon",
        population: "27.2 million",
        currency: "Central African CFA Franc (XAF)",
        language: "French, English",
        capital: "Yaoundé",
        area: "475,442 km²",
        continent: "Africa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Cameroon.svg"
      },
      {
        name: "Bahrain",
        population: "1.7 million",
        currency: "Bahraini Dinar (BHD)",
        language: "Arabic",
        capital: "Manama",
        area: "778 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Bahrain.svg"
      },
      {
        name: "Lebanon",
        population: "6.8 million",
        currency: "Lebanese Pound (LBP)",
        language: "Arabic",
        capital: "Beirut",
        area: "10,452 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Lebanon.svg"
      }
      
      
  ];

  export const countriesDataEs = [
    {
        name: 'Francia',
        population: '67,1 millones',
        currency: 'Euro (EUR)',
        language: 'Francés',
        capital: 'París',
        area: '551 695 km²',
        continent: 'Europa',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_France.svg'
      },
      {
        name: 'España',
        population: '47,3 millones',
        currency: 'Euro (EUR)',
        language: 'Español',
        capital: 'Madrid',
        area: '505 990 km²',
        continent: 'Europa',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Spain.svg'
      },
      {
        name: 'Estados Unidos',
        population: '331 millones',
        currency: 'Dólar (USD)',
        language: 'Inglés',
        capital: 'Washington, D.C.',
        area: '9,83 millones de km²',
        continent: 'América del Norte',
        flag: 'https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg'
      },
      {
        name: 'Italia',
        population: '60,4 millones',
        currency: 'Euro (EUR)',
        language: 'Italiano',
        capital: 'Roma',
        area: '301 340 km²',
        continent: 'Europa',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/0/03/Flag_of_Italy.svg'
      },
      {
        name: 'China',
        population: '1,41 mil millones',
        currency: 'Yuan (CNY)',
        language: 'Chino',
        capital: 'Pekín',
        area: '9,597 millones de km²',
        continent: 'Asia',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg'
      },
      {
        name: 'Reino Unido',
        population: '67,1 millones',
        currency: 'Libra (GBP)',
        language: 'Inglés',
        capital: 'Londres',
        area: '242 495 km²',
        continent: 'Europa',
        flag: 'https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg'
      },
      {
        name: 'México',
        population: '126 millones',
        currency: 'Peso mexicano (MXN)',
        language: 'Español',
        capital: 'Ciudad de México',
        area: '1,96 millones de km²',
        continent: 'América del Norte',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg'
      },
      {
        name: 'Canadá',
        population: '37,7 millones',
        currency: 'Dólar canadiense (CAD)',
        language: 'Inglés, Francés',
        capital: 'Ottawa',
        area: '9,98 millones de km²',
        continent: 'América del Norte',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Canada_%28Pantone%29.svg'
      },
      {
        name: 'Turquía',
        population: '84,3 millones',
        currency: 'Lira turca (TRY)',
        language: 'Turco',
        capital: 'Ankara',
        area: '783 356 km²',
        continent: 'Asia',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg'
      },
      {
        name: 'Alemania',
        population: '83,2 millones',
        currency: 'Euro (EUR)',
        language: 'Alemán',
        capital: 'Berlín',
        area: '357 022 km²',
        continent: 'Europa',
        flag: 'https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg'
      },
      {
        name: 'Japón',
        population: '126 millones',
        currency: 'Yen japonés (JPY)',
        language: 'Japonés',
        capital: 'Tokio',
        area: '377 975 km²',
        continent: 'Asia',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Flag_of_Japan.svg'
      },
      {
        name: 'Tailandia',
        population: '69,8 millones',
        currency: 'Baht tailandés (THB)',
        language: 'Tailandés',
        capital: 'Bangkok',
        area: '513 120 km²',
        continent: 'Asia',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg'
      },
      {
        name: 'Emiratos Árabes Unidos',
        population: '9,89 millones',
        currency: 'Dirham (AED)',
        language: 'Árabe',
        capital: 'Abu Dabi',
        area: '83 600 km²',
        continent: 'Asia',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg'
      },
      {
        name: 'Egipto',
        population: '104 millones',
        currency: 'Libra egipcia (EGP)',
        language: 'Árabe egipcio',
        capital: 'El Cairo',
        area: '1 010 408 km²',
        continent: 'África',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg'
      },
      {
        name: 'Bulgaria',
        population: '6,92 millones',
        currency: 'Lev búlgaro (BGN)',
        language: 'Búlgaro',
        capital: 'Sofía',
        area: '110 879 km²',
        continent: 'Europa',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg'
      },
      {
        name: 'Portugal',
        population: '10,3 millones',
        currency: 'Euro (EUR)',
        language: 'Portugués',
        capital: 'Lisboa',
        area: '92 212 km²',
        continent: 'Europa',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg'
      },
      {
        name: 'República Dominicana',
        population: '10,9 millones',
        currency: 'Peso dominicano (DOP)',
        language: 'Español',
        capital: 'Santo Domingo',
        area: '48 671 km²',
        continent: 'América del Norte',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg'
      },
      {
        name: 'Túnez',
        population: '11,7 millones',
        currency: 'Dinar tunecino (TND)',
        language: 'Árabe',
        capital: 'Túnez',
        area: '163 610 km²',
        continent: 'África',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg'
      },{
        name: 'Hungría',
        population: '9,7 millones',
        currency: 'Forinto húngaro (HUF)',
        language: 'Húngaro',
        capital: 'Budapest',
        area: '93 030 km²',
        continent: 'Europa',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg',
      },
      {
        name: 'Suiza',
        population: '8,6 millones',
        currency: 'Franco suizo (CHF)',
        language: 'Alemán, Francés, Italiano, Romanche',
        capital: 'Berna',
        area: '41 290 km²',
        continent: 'Europa',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Switzerland.svg',
      },
      {
        name: 'Croacia',
        population: '4,07 millones',
        currency: 'Kuna croata (HRK)',
        language: 'Croata',
        capital: 'Zagreb',
        area: '56 594 km²',
        continent: 'Europa',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg',
      },
      {
        name: 'Grecia',
        population: '10,4 millones',
        currency: 'Euro (EUR)',
        language: 'Griego',
        capital: 'Atenas',
        area: '131 957 km²',
        continent: 'Europa',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg',
      },
      {
        name: 'Austria',
        population: '8,9 millones',
        currency: 'Euro (EUR)',
        language: 'Alemán',
        capital: 'Viena',
        area: '83 879 km²',
        continent: 'Europa',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg',
      },
      {
        name: 'India',
        population: '1,366 mil millones',
        currency: 'Rupia india (INR)',
        language: 'Hindi, Inglés y 21 otros idiomas',
        capital: 'Nueva Delhi',
        area: '3 287 263 km²',
        continent: 'Asia',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_India.svg',
      },
      {
        name: 'Cuba',
        population: '11,3 millones',
        currency: 'Peso cubano (CUP)',
        language: 'Español',
        capital: 'La Habana',
        area: '109 884 km²',
        continent: 'América del Norte',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg',
      },
      {
        name: 'Colombia',
        population: '50,9 millones',
        currency: 'Peso colombiano (COP)',
        language: 'Español',
        capital: 'Bogotá',
        area: '1 141 748 km²',
        continent: 'América del Sur',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg',
      },
      {
        name: 'República Checa',
        population: '10,7 millones',
        currency: 'Corona checa (CZK)',
        language: 'Checo',
        capital: 'Praga',
        area: '78 866 km²',
        continent: 'Europa',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg',
      },
      {
        name: 'Eslovaquia',
        population: '5,4 millones',
        currency: 'Euro (EUR)',
        language: 'Eslovaco',
        capital: 'Bratislava',
        area: '49 035 km²',
        continent: 'Europa',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Slovakia.svg',
      },
      {
        name: 'Países Bajos',
        population: '17,4 millones',
        currency: 'Euro (EUR)',
        language: 'Neerlandés',
        capital: 'Ámsterdam',
        area: '41 543 km²',
        continent: 'Europa',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg',
      },
      {
        name: 'Bélgica',
        population: '11,5 millones',
        currency: 'Euro (EUR)',
        language: 'Neerlandés, Francés, Alemán',
        capital: 'Bruselas',
        area: '30 528 km²',
        continent: 'Europa',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg',
      },
      {
        name: 'Brasil',
        population: '213,3 millones',
        currency: 'Real brasileño (BRL)',
        language: 'Portugués',
        capital: 'Brasilia',
        area: '8 515 767 km²',
        continent: 'América del Sur',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Brazil.svg',
      },
      {
        name: 'Argentina',
        population: '45,4 millones',
        currency: 'Peso argentino (ARS)',
        language: 'Español',
        capital: 'Buenos Aires',
        area: '2 780 400 km²',
        continent: 'América del Sur',
        flag: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg',
      },{
        name: "Argentina",
        population: "45,4 millones",
        currency: "Peso argentino (ARS)",
        language: "Español",
        capital: "Buenos Aires",
        area: "2 780 400 km²",
        continent: "América del Sur",
        flag: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg"
      },
      {
        name: "Eslovenia",
        population: "2,1 millones",
        currency: "Euro (EUR)",
        language: "Esloveno",
        capital: "Liubliana",
        area: "20 273 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Flag_of_Slovenia.svg"
      },
      {
        name: "Albania",
        population: "2,9 millones",
        currency: "Lek albanés (ALL)",
        language: "Albanés",
        capital: "Tirana",
        area: "28 748 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Albania.svg"
      },
      {
        name: "Bosnia y Herzegovina",
        population: "3,3 millones",
        currency: "Marco bosnio (BAM)",
        language: "Bosnio, Croata, Serbio",
        capital: "Sarajevo",
        area: "51 197 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bosnia_and_Herzegovina.svg"
      },
      {
        name: "Serbia",
        population: "6,7 millones",
        currency: "Dinar serbio (RSD)",
        language: "Serbio",
        capital: "Belgrado",
        area: "88 361 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Serbia.svg"
      },
      {
        name: "Montenegro",
        population: "622 000",
        currency: "Euro (EUR)",
        language: "Montenegrino",
        capital: "Podgorica",
        area: "13 812 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Montenegro.svg"
      },
      {
        name: "Macedonia",
        population: "2,1 millones",
        currency: "Denar macedonio (MKD)",
        language: "Macedonio",
        capital: "Skopie",
        area: "25 713 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/f/f8/Flag_of_North_Macedonia.svg"
      },
      {
        name: "Suecia",
        population: "10,4 millones",
        currency: "Corona sueca (SEK)",
        language: "Sueco",
        capital: "Estocolmo",
        area: "450 295 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Sweden.svg"
      },
      {
        name: "Finlandia",
        population: "5,5 millones",
        currency: "Euro (EUR)",
        language: "Finlandés, Sueco",
        capital: "Helsinki",
        area: "338 455 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg"
      },
      {
        name: "Dinamarca",
        population: "5,8 millones",
        currency: "Corona danesa (DKK)",
        language: "Danés",
        capital: "Copenhague",
        area: "42 933 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg"
      },
      {
        name: "Noruega",
        population: "5,4 millones",
        currency: "Corona noruega (NOK)",
        language: "Noruego",
        capital: "Oslo",
        area: "385 207 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg"
      },
      {
        name: "Islandia",
        population: "372 000",
        currency: "Corona islandesa (ISK)",
        language: "Islandés",
        capital: "Reikiavik",
        area: "103 000 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg"
      },
      {
        name: "Luxemburgo",
        population: "645 000",
        currency: "Euro (EUR)",
        language: "Luxemburgués, Francés, Alemán",
        capital: "Luxemburgo",
        area: "2 586 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Luxembourg.svg"
      },
      {
        name: "Rumanía",
        population: "19,3 millones",
        currency: "Leu rumano (RON)",
        language: "Rumano",
        capital: "Bucarest",
        area: "238 397 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg"
      },
      {
        name: "Estonia",
        population: "1,3 millones",
        currency: "Euro (EUR)",
        language: "Estonio",
        capital: "Tallin",
        area: "45 227 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Flag_of_Estonia.svg"
      },
      {
        name: "Letonia",
        population: "1,8 millones",
        currency: "Euro (EUR)",
        language: "Letón",
        capital: "Riga",
        area: "64 589 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Latvia.svg"
      },
      {
        name: "Lituania",
        population: "2,8 millones",
        currency: "Euro (EUR)",
        language: "Lituano",
        capital: "Vilna",
        area: "65 300 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Lithuania.svg"
      },
      {
        name: "Perú",
        population: "33,7 millones",
        currency: "Sol peruano (PEN)",
        language: "Español",
        capital: "Lima",
        area: "1 285 216 km²",
        continent: "América del Sur",
        flag: "https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Peru.svg"
      },
      {
        name: "Ecuador",
        population: "18 millones",
        currency: "Dólar estadounidense (USD)",
        language: "Español",
        capital: "Quito",
        area: "283 561 km²",
        continent: "América del Sur",
        flag: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Ecuador.svg"
      },
      {
        name: "Chile",
        population: "19,5 millones",
        currency: "Peso chileno (CLP)",
        language: "Español",
        capital: "Santiago de Chile",
        area: "756 096 km²",
        continent: "América del Sur",
        flag: "https://upload.wikimedia.org/wikipedia/commons/7/78/Flag_of_Chile.svg"
      },
      {
        name: "Bolivia",
        population: "12,2 millones",
        currency: "Boliviano (BOB)",
        language: "Español, Quechua, Aimara",
        capital: "Sucre",
        area: "1 098 581 km²",
        continent: "América del Sur",
        flag: "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Bolivia.svg"
      },{
        name: "Paraguay",
        population: "7,3 millones",
        currency: "Guaraní paraguayo (PYG)",
        language: "Español, Guaraní",
        capital: "Asunción",
        area: "406 752 km²",
        continent: "América del Sur",
        flag: "https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Paraguay.svg"
      }, 
      {
        name: "Costa Rica",
        population: "5,2 millones",
        currency: "Colón costarricense (CRC)",
        language: "Español",
        capital: "San José",
        area: "51 100 km²",
        continent: "América del Norte",
        flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Costa_Rica_%28state%29.svg"
      },
      {
        name: "Panamá",
        population: "4,4 millones",
        currency: "Balboa (PAB), Dólar estadounidense (USD)",
        language: "Español",
        capital: "Ciudad de Panamá",
        area: "75 417 km²",
        continent: "América del Norte",
        flag: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Flag_of_Panama.svg"
      },
      {
        name: "Honduras",
        population: "10 millones",
        currency: "Lempira hondureña (HNL)",
        language: "Español",
        capital: "Tegucigalpa",
        area: "112 492 km²",
        continent: "América del Norte",
        flag: "https://upload.wikimedia.org/wikipedia/commons/8/82/Flag_of_Honduras.svg"
      },
      {
        name: "Hong Kong",
        population: "7,5 millones",
        currency: "Dólar de Hong Kong (HKD)",
        language: "Chino, Inglés",
        capital: "Hong Kong",
        area: "1 104 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Flag_of_Hong_Kong.svg"
      },
      {
        name: "Vietnam",
        population: "97,3 millones",
        currency: "Dong vietnamita (VND)",
        language: "Vietnamita",
        capital: "Hanói",
        area: "331 212 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg"
      },
      {
        name: "Malasia",
        population: "32,7 millones",
        currency: "Ringgit malayo (MYR)",
        language: "Malayo",
        capital: "Kuala Lumpur",
        area: "330 803 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg"
      },
      {
        name: "Irlanda",
        population: "4,9 millones",
        currency: "Euro (EUR)",
        language: "Irlandés, Inglés",
        capital: "Dublín",
        area: "70 273 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Ireland.svg"
      },
      {
        name: "Indonesia",
        population: "273,5 millones",
        currency: "Rupia indonesia (IDR)",
        language: "Indonesio",
        capital: "Yakarta",
        area: "1 904 569 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg"
      },
      {
        name: "Irán",
        population: "83 millones",
        currency: "Rial iraní (IRR)",
        language: "Persa",
        capital: "Teherán",
        area: "1 648 195 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg"
      },
      {
        name: "Israel",
        population: "9,2 millones",
        currency: "Nuevo shequel israelí (ILS)",
        language: "Hebreo",
        capital: "Jerusalén",
        area: "20 770 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg"
      },
      {
        name: "Chipre",
        population: "1,2 millones",
        currency: "Euro (EUR)",
        language: "Griego, Turco",
        capital: "Nicosia",
        area: "9 251 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cyprus.svg"
      },
      {
        name: "Marruecos",
        population: "36,9 millones",
        currency: "Dirham marroquí (MAD)",
        language: "Árabe, Bereber",
        capital: "Rabat",
        area: "446 550 km²",
        continent: "África",
        flag: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg"
      },
      {
        name: "Maldivas",
        population: "530 000",
        currency: "Rupia maldiva (MVR)",
        language: "Maldivo",
        capital: "Malé",
        area: "298 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Maldives.svg"
      },
      {
        name: "Madagascar",
        population: "27,7 millones",
        currency: "Ariary malgache (MGA)",
        language: "Malgache, Francés",
        capital: "Antananarivo",
        area: "587 041 km²",
        continent: "África",
        flag: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Madagascar.svg"
      },
      {
        name: "Australia",
        population: "25,4 millones",
        currency: "Dólar australiano (AUD)",
        language: "Inglés",
        capital: "Canberra",
        area: "7 692 024 km²",
        continent: "Australia y Oceanía",
        flag: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Australia.svg"
      },
      {
        name: "Nueva Zelanda",
        population: "5,1 millones",
        currency: "Dólar neozelandés (NZD)",
        language: "Inglés, Maorí",
        capital: "Wellington",
        area: "268 021 km²",
        continent: "Australia y Oceanía",
        flag: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg"
      },
      {
        name: "Mauricio",
        population: "1,3 millones",
        currency: "Rupia mauriciana (MUR)",
        language: "Inglés, Criollo mauriciano, Francés",
        capital: "Puerto Luis",
        area: "2 040 km²",
        continent: "África",
        flag: "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Mauritius.svg"
      },
      {
        name: "Jamaica",
        population: "2,9 millones",
        currency: "Dólar jamaiquino (JMD)",
        language: "Inglés",
        capital: "Kingston",
        area: "10 991 km²",
        continent: "América del Norte",
        flag: "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Jamaica.svg"
      },
      {
        name: "Nepal",
        population: "29,1 millones",
        currency: "Rupia nepalesa (NPR)",
        language: "Nepalí",
        capital: "Katmandú",
        area: "147 516 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/9/9b/Flag_of_Nepal.svg"
      },{
        name: "Arabia Saudita",
        population: "34,8 millones",
        currency: "Riyal saudí (SAR)",
        language: "Árabe",
        capital: "Riad",
        area: "2 149 690 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg"
      },
      {
        name: "Omán",
        population: "5,1 millones",
        currency: "Riyal omaní (OMR)",
        language: "Árabe",
        capital: "Mascate",
        area: "309 500 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Oman.svg"
      },
      {
        name: "Corea del Sur",
        population: "51,3 millones",
        currency: "Won surcoreano (KRW)",
        language: "Coreano",
        capital: "Seúl",
        area: "100 210 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg"
      },
      {
        name: "Zimbabue",
        population: "15,2 millones",
        currency: "Dólar zimbabuense (ZWL)",
        language: "Inglés, Sindebele, Shona",
        capital: "Harare",
        area: "390 757 km²",
        continent: "África",
        flag: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Flag_of_Zimbabwe.svg"
      },
      {
        name: "Kenia",
        population: "54,9 millones",
        currency: "Chelín keniano (KES)",
        language: "Swahili, Inglés",
        capital: "Nairobi",
        area: "580 367 km²",
        continent: "África",
        flag: "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Kenya.svg"
      },
      {
        name: "Uruguay",
        population: "3,5 millones",
        currency: "Peso uruguayo (UYU)",
        language: "Español",
        capital: "Montevideo",
        area: "176 215 km²",
        continent: "América del Sur",
        flag: "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Uruguay.svg"
      },
      {
        name: "Filipinas",
        population: "111,1 millones",
        currency: "Peso filipino (PHP)",
        language: "Filipino",
        capital: "Manila",
        area: "300 000 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg"
      },
      {
        name: "Kazajistán",
        population: "18,8 millones",
        currency: "Tenge kazajo (KZT)",
        language: "Kazajo, Ruso",
        capital: "Nur-Sultán",
        area: "2 724 900 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kazakhstan.svg"
      },
      {
        name: "Georgia",
        population: "3,7 millones",
        currency: "Lari georgiano (GEL)",
        language: "Georgiano",
        capital: "Tiflis",
        area: "69 700 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Georgia.svg"
      },
      {
        name: "Azerbaiyán",
        population: "10,2 millones",
        currency: "Manat azerbaiyano (AZN)",
        language: "Azerbaiyano",
        capital: "Bakú",
        area: "86 600 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Azerbaijan.svg"
      },
      {
        name: "Ucrania",
        population: "41,8 millones",
        currency: "Grivna ucraniana (UAH)",
        language: "Ucraniano",
        capital: "Kiev",
        area: "603 500 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg"
      },
      {
        name: "Rusia",
        population: "146,7 millones",
        currency: "Rublo ruso (RUB)",
        language: "Ruso",
        capital: "Moscú",
        area: "17 098 242 km²",
        continent: "Europa y Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Russia.svg"
      },
      {
        name: "Tanzania",
        population: "58,0 millones",
        currency: "Chelín tanzano (TZS)",
        language: "Swahili, Inglés",
        capital: "Dodoma",
        area: "947 303 km²",
        continent: "África",
        flag: "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tanzania.svg"
      },
      {
        name: "Catar",
        population: "2,8 millones",
        currency: "Rial catarí (QAR)",
        language: "Árabe",
        capital: "Doha",
        area: "11 586 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg"
      },
      {
        name: "Malta",
        population: "0,5 millones",
        currency: "Euro (EUR)",
        language: "Maltés, Inglés",
        capital: "La Valeta",
        area: "316 km²",
        continent: "Europa",
        flag: "https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Malta.svg"
      },
      {
        name: "Sri Lanka",
        population: "21,4 millones",
        currency: "Rupia de Sri Lanka (LKR)",
        language: "Cingalés, Tamil",
        capital: "Sri Jayawardenepura Kotte",
        area: "65 610 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Sri_Lanka.svg"
      },{
        name: "Sudáfrica",
        population: "59,3 millones",
        currency: "Rand sudafricano (ZAR)",
        language: "Afrikáans, Inglés, Sotho, Zulú",
        capital: "Pretoria, Ciudad del Cabo, Bloemfontein",
        area: "1 221 037 km²",
        continent: "África",
        flag: "https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg"
      },
      {
        name: "Jordania",
        population: "10,2 millones",
        currency: "Dinar jordano (JOD)",
        language: "Árabe",
        capital: "Amán",
        area: "89 342 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Jordan.svg"
      },
      {
        name: "Ghana",
        population: "31,1 millones",
        currency: "Cedi ghanés (GHS)",
        language: "Inglés",
        capital: "Acra",
        area: "238 535 km²",
        continent: "África",
        flag: "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg"
      },
      {
        name: "Camerún",
        population: "27,2 millones",
        currency: "Franco CFA de África Central (XAF)",
        language: "Francés, Inglés",
        capital: "Yaundé",
        area: "475 442 km²",
        continent: "África",
        flag: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Cameroon.svg"
      },
      {
        name: "Baréin",
        population: "1,7 millones",
        currency: "Dinar bareiní (BHD)",
        language: "Árabe",
        capital: "Manama",
        area: "778 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Bahrain.svg"
      },
      {
        name: "Líbano",
        population: "6,8 millones",
        currency: "Libra libanesa (LBP)",
        language: "Árabe",
        capital: "Beirut",
        area: "10 452 km²",
        continent: "Asia",
        flag: "https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Lebanon.svg"
      }
      
    
    ]
  